### ISSUE TITLE
Update XML not showing the highest version

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#72]
@Llewellynvdm 
The update XML shows the last uploaded version, not the highest one.
https://update.joomla.org/language/translationlist_4.xml

I would expect it shows the incremental versions.
Which means 4.0.1.1 instead of 4.0.0.10 for English AU.
https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-english-australia

Can you take a look?
CC @particthistle

**Comment by Llewellynvdm** [comment]
Hmm we are not modeling the version but taking it directly from the system.

As you can see here https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/site/models/export.php#L185

This should mean the data is not correct in the database.... well that is what I think, it is not the export making changes.

**Comment by Llewellynvdm** [comment]
So @wilsonge [here we do declare](https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/site/models/export.php#L261) to be latest ... why does it return the 4.0.0.10 and not 4.1.1? @conconnl is there a 4.1.1 in the system?

**Comment by conconnl** [comment]
The order display on the website seems to be the order of upload. 
That is probably why 4.0.0.10 is in the xml instead of 4.0.1.1 as the .10 was uploaded as last one.

**Comment by Llewellynvdm** [comment]
So its not using the version number to see what is the latest... but the upload date. Should this change?

**Comment by particthistle** [comment]
(See note on issue 71)[https://github.com/joomla-extensions/pkg_languagepack/issues/71#issuecomment-905188966]

@Llewellynvdm wrote:
> why does it return the 4.0.0.10 and not 4.0.1.1?
The language packs in the list are manually populated by the proofreader doing the upload, and as @conconnl indicated, currently it's displayed by order of upload not version - that's how it should be IMO... I just broke the version ordering by mixing things up. 

So in the example:
- I'd been trying to correct several things and ended up not updating version tags properly when I got to 4.0.1.1.
- I then found 4.0.1.1 installed on 4.0.0 showed up with a version warning
![image](https://user-images.githubusercontent.com/5515866/131289087-10d86ea0-cccb-483d-a210-eb83fba4c1d4.png)
- Crowdin additionally had an 18 hour window last week where it was blanking out the version in the xml files (it resolved itself on Monday and has been stable since)
- I then uploaded a new version out of sequence which then caused the issue here.
- That's been further resolved by the upload of 4.0.1.2 which put it back into sequence but exposed the issue with the ordering.

Additional notes:
- Proofreaders put in what the version will be numbered in the upload process, rather than the download system pulling it from pkg-<language>.xml file. This value is then what's used in https://update.joomla.org/language/translationlist_4.xml
- Proofreaders also need to update the versions in 3 sets of install.xml (and I note [/api/language/install.xml](https://github.com/joomla/joomla-cms/blob/4.0-dev/api/language/en-GB/install.xml) is not in @wilsonge "[Reset to Dev](https://github.com/joomla/joomla-cms/commit/1bf44a5608c0a55c7db05e79189bfde945087d4e)" updates. 
- If proofreaders have not updated the 7 files with new version numbers + set the version number to match when they upload a new language pack, then the system ends up with various out of sync issues.
- Proofreaders can not delete a language pack that they've uploaded in error. Is there a technical need to retain outdated language packs?


Having discovered all the above during the process, it's being added to Proofreader instructions to ensure all of it's covered by new proofreaders going forward.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/commit/8e6f8d463ff0f20eba4958e2534ad9664553d938 install.xml added for the next release

**Comment by HLeithner** [comment]
Seems to be fixed. I'm closing this.
